api:
    build: ./env/api/
    ports:
        - "8080:8080"
    links:
        - mongo
        - elasticsearch
    volumes:
        - /srv/openstore/openstore-api:/srv/openstore

web:
    build: ./env/web/
    ports:
        - "8081:8081"
    volumes:
        - /srv/openstore/openstore-web:/srv/openstore

mongo:
    image: mongo
    ports:
        - "27017:27017"
    volumes:
        - /data/db:/data/db
        - /srv/openstore/openstore-api:/srv/openstore

elasticsearch:
    image: elasticsearch:2-alpine
    ports:
        - "9200:9200"
    volumes:
        - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data
