version: "3"
services:
  api:
    image: theopenstore/api
    ports:
      - "8082:8080"
    volumes:
      - ./openstore-api:/srv/openstore

  web:
    image: node:10
    command: npm run serve
    working_dir: /srv/openstore
    ports:
      - "8081:8081"
    volumes:
      - ./openstore-web:/srv/openstore

  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
    volumes:
      - /data/db:/data/db
      - ./openstore-api:/srv/openstore

  elasticsearch:
    image: elasticsearch:2-alpine
    ports:
      - "9200:9200"
    volumes:
      - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data

  nginx:
    image: nginx
    ports:
        - "8080:80"
    volumes:
      - ./docker/proxy.conf:/etc/nginx/conf.d/default.conf
