version: "3"
services:
  api:
    build:
      context: ./docker/api
    ports:
      - "8082:8080"
    volumes:
      - ./openstore-api:/srv/openstore
      - ./.data/clicks:/srv/openstore-data
      - ./.data/icons:/srv/openstore-icons
      - ./.data/screenshots:/srv/openstore-screenshots
    environment:
      - DATA_DIR=/srv/openstore-data
      - ICON_DIR=/srv/openstore-icons
      - IMAGE_DIR=/srv/openstore-screenshots

  web:
    image: node:20
    command: npm run serve
    working_dir: /srv/openstore
    ports:
      - "8081:8081"
    volumes:
      - ./openstore-web:/srv/openstore

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - ./.data/db:/data/db
      - ./openstore-api:/srv/openstore

  elasticsearch:
    image: elasticsearch:2-alpine
    ports:
      - "9200:9200"
    volumes:
      - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data

  nginx:
    image: nginx
    ports:
        - "80:80"
    volumes:
      - ./docker/proxy.conf:/etc/nginx/conf.d/default.conf
      - ./.data/icons:/srv/openstore-icons
      - ./.data/screenshots:/srv/openstore-screenshots
